services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"

# USERS MS
  users-ms:
    build: ./users-ms
    ports:
      - "${USERS_MS_PORT}:${USERS_MS_PORT}"
    volumes:
      - ./users-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:admin@users-db:5432/usersdb